/*
You have to use '{}' when it has a possibility of exception
TWO ways to make it excepted
1. Try-Catch -> my own business
2. Throw -> give responsibility to the one that called itself.
Try{} is the place where you have to write the sentences that has a possibility of exception
Catch{} is a place where alternative options are written (!Only when an exception occurred in try{}!)
Finally{} is a place where same commands are written which try{} and catch{} both have


EXCEPTION HANDLER
-> 2 WAYS
1. SURROUND with TRY-CATCH
2. THROWS

-> TRY-CATCH-FINALLY
1. try{}
    -> () : where CLASS that should AUTO RETURN belongs
    -> {} : where CODE that has possibility to be excepted belongs
2. catch{} : ALTERNATIVE OPTION that an exception occurred in try{}
3. finally{} : FINAL EXCEPTION (ex. resource RETURN)

-> ERROR? EXCEPTION?
-> If(exception) exists, It must be EXCEPTION
-> Rest of red underlines would be ERRORS
-> If two or more things to solve, USE THROWS! or DIY...                                             

 */

